### ISSUE TITLE
Feature Suggestion, please

### ISSUE THREAD

**Issue by akissz** [htmsk138/noto-simple#4]
1.) add simple setting in theme options to move site-navigation/menus above "site-branding" in header. So there are 2 settings, the default or above or maybe named "menu top", etc.

2.) in menu mobile view... and add feature to adjust position of menu spacing from top of page in mobile view. this way you can have the menu at the top of the page or spaced down a set value of pixels how you have it by default now spaced down. if the value is zero then the close menu X would be placed in the corner on top of the menu and then it looks better for some sites. -- also please remove drop shadow from menu on mobile menu.

**Comment by htmsk138** [comment]
@akissz 
Hi, thanks for the suggestions.

But I'm not sure if I want to provide these options, because

1.) Having two menus in the header seems confusing, and I'd rather not place any navigation above the branding.

2.) Please consider using Additional CSS feature (in theme customise screen) for small adjustments. Add this snippet to get what you want:

```css
@media (max-width: 767px) {
  /* Remove shadow */
  .main-navigation.toggled {
    box-shadow: none;
  }

  /* Menu position at page top */
  .main-navigation {
    margin-top: 40px;
  }
  .menu-toggle {
    margin: 0;
    top: -40px;
  }
}
```

I intend to keep the theme as simple as possible so that it can give child theme developers more flexibilities.

Thank you for your support anyway!
